# Generated by Django 4.1.4 on 2023-02-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="item",
            new_name="product",
        ),
    ]
