# Generated by Django 4.1.4 on 2023-03-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_sizes_image"),
        ("project", "0003_remove_contact_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="product_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="contacts",
                to="catalog.productcolor",
                verbose_name="Колір",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="product_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="contacts",
                to="catalog.productsize",
                verbose_name="Розмір",
            ),
        ),
    ]
