# Generated by Django 4.1.4 on 2023-03-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_product_categories"),
        ("project", "0005_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="product_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="catalog.productcolor",
                verbose_name="Колір",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="product_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="catalog.productsize",
                verbose_name="Розмір",
            ),
        ),
    ]
