# Generated by Django 4.1.4 on 2023-02-26 11:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Найменування",
                    ),
                ),
            ],
            options={
                "verbose_name": "Найменування характеристики",
                "verbose_name_plural": "Найменування характеристик",
            },
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=256, verbose_name="Назва для пошуку"),
                ),
                (
                    "title",
                    ckeditor.fields.RichTextField(
                        blank=True, max_length=4096, null=True, verbose_name="Значення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Значення характеристик",
                "verbose_name_plural": "Значення характеристик",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Загловок")),
                (
                    "image",
                    models.ImageField(
                        max_length=512, upload_to="item", verbose_name="Зображення"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Короткий опис"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(blank=True, null=True, verbose_name="Ціна"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активність"),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Сортування"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="ProductAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Найменування",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=512,
                        upload_to="advantages/",
                        verbose_name="Зображення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення властивостей товару",
                "verbose_name_plural": "Зображення властивостей товару",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Найменування",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Унікальний запис",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=512, upload_to="item", verbose_name="Зображення"
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Сортування"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активність"),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=512,
                        upload_to="product",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Альт картинки"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення товару",
                "verbose_name_plural": "Зображення товару",
            },
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_features",
                        to="catalog.feature",
                        verbose_name="Назва характеристики",
                    ),
                ),
                (
                    "feature_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_features",
                        to="catalog.featurevalue",
                        verbose_name="Значення характеристики",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_features",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика товару",
                "verbose_name_plural": "Характеристики товару",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="advantages",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.productadvantage",
                verbose_name="Властивості",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.productcategory",
                verbose_name="Категорія",
            ),
        ),
    ]
