# Generated by Django 4.1.4 on 2023-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_productadvantage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=512, null=True, verbose_name="Унікальний запис"
            ),
        ),
    ]
