# Generated by Django 4.1.4 on 2023-02-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(blank=True, null=True, verbose_name="Мета-опис"),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_keys",
            field=models.TextField(blank=True, null=True, verbose_name="Мета-ключі"),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.TextField(blank=True, null=True, verbose_name="Мета-загловок"),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Створено"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Оновлено"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Ім'я"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="Текст"
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(verbose_name="Оцінка")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активність"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Відгук",
                "verbose_name_plural": "Відгуки",
            },
        ),
    ]
