# Generated by Django 4.1.4 on 2023-02-28 14:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_meta_description_product_meta_keys_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Найменування",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Унікальний запис",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        image_field=None,
                        max_length=18,
                        samples=None,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product color",
                "verbose_name_plural": "Product color",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Кількість"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(
                blank=True, to="catalog.productcolor", verbose_name="Colors"
            ),
        ),
    ]
