# Generated by Django 4.1.4 on 2023-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productcolor_product_quantity_product_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Найменування",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Унікальний запис",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розмір продуктів",
                "verbose_name_plural": "Розміри продуктів",
            },
        ),
        migrations.AlterModelOptions(
            name="productcolor",
            options={
                "verbose_name": "Колір продукту",
                "verbose_name_plural": "Кольори продуктів",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(
                blank=True, to="catalog.productcolor", verbose_name="Кольори"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, to="catalog.productsize", verbose_name="Розміри"
            ),
        ),
    ]
