# Generated by Django 4.1.4 on 2023-03-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productsize_alter_productcolor_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="phone",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="телефон"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="full_name",
            field=models.CharField(default=" f", max_length=256, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.CharField(default=" f", max_length=1024, verbose_name="Текст"),
            preserve_default=False,
        ),
    ]
