# Generated by Django 4.1.4 on 2023-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_review_email_review_phone_alter_review_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Загловок"
            ),
        ),
    ]
