# Generated by Django 4.1.4 on 2023-03-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes_image",
            field=models.ImageField(
                blank=True,
                max_length=512,
                upload_to="item",
                verbose_name="Зображення сітки розмірів",
            ),
        ),
    ]
