# Generated by Django 4.1.4 on 2023-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_sizes_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="similars",
            field=models.ManyToManyField(
                blank=True, to="catalog.product", verbose_name="Подібні"
            ),
        ),
    ]
