# Generated by Django 4.1.4 on 2023-03-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_remove_featurevalue_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="video_url",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Посилання на відео"
            ),
        ),
    ]
