# Generated by Django 4.1.4 on 2023-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_product_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                to="catalog.productcategory", verbose_name="Категорія"
            ),
        ),
    ]
