# Generated by Django 4.1.4 on 2023-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_remove_product_category_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products",
                to="catalog.productcategory",
                verbose_name="Категорія",
            ),
        ),
    ]
