# Generated by Django 3.2.13 on 2023-03-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.SlugField(blank=True, max_length=512, null=True, verbose_name='Артикль'),
        ),
    ]
