# Generated by Django 4.2 on 2023-04-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20230324_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeature',
            options={'ordering': ('id',), 'verbose_name': 'Характеристика товару', 'verbose_name_plural': 'Характеристики товару'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['title'], 'verbose_name': 'Розмір продуктів', 'verbose_name_plural': 'Розміри продуктів'},
        ),
    ]
