# Generated by Django 3.2.8 on 2023-12-03 14:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_productfeature_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, unique=True),
        ),
    ]
