# Generated by Django 3.2.13 on 2023-12-25 15:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_productcolor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True),
        ),
    ]
