# Generated by Django 4.1.4 on 2023-02-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productsize_alter_productcolor_options_and_more"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartproduct",
            options={
                "verbose_name": "Товар у кошику",
                "verbose_name_plural": "Товари в кошиках",
            },
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="product_color",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cart_products",
                to="catalog.productcolor",
                verbose_name="Колір",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="product_size",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cart_products",
                to="catalog.productsize",
                verbose_name="Розмір",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_products",
                to="cart.cart",
                verbose_name="Кошик",
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_products",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="quantity",
            field=models.PositiveSmallIntegerField(verbose_name="Кількість"),
        ),
    ]
