# Generated by Django 4.1.4 on 2023-02-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("s_content", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="meta_descr",
            new_name="meta_description",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="meta_key",
            new_name="meta_keys",
        ),
    ]
