# Generated by Django 4.1.4 on 2023-02-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("s_content", "0002_rename_meta_descr_site_meta_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.TextField(blank=True, null=True, verbose_name="Meta-title"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Meta-description"
                    ),
                ),
                (
                    "meta_keys",
                    models.TextField(blank=True, null=True, verbose_name="Meta-keys"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Добавляється автоматично після створення об'єкту",
                        max_length=512,
                        null=True,
                        verbose_name="Унікальний запис",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мета дані",
                "verbose_name_plural": "Мета дані",
            },
        ),
    ]
