# Generated by Django 3.2.13 on 2023-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_content', '0004_site_created_site_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='public_privacy',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='site/', verbose_name='Price File'),
        ),
    ]
