# Generated by Django 4.1.4 on 2023-02-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=512, verbose_name="Full name"),
                ),
                ("phone", models.CharField(max_length=512, verbose_name="Phone")),
                ("email", models.CharField(max_length=512, verbose_name="Email")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Street"
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Apartment"
                    ),
                ),
                ("city", models.CharField(max_length=512, verbose_name="City")),
                ("state", models.CharField(max_length=512, verbose_name="State")),
                (
                    "postal_code",
                    models.PositiveSmallIntegerField(verbose_name="Postal code"),
                ),
                (
                    "total_price",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Total price"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("CS", "Cashless"), ("UR", "Upon receipt")],
                        max_length=64,
                        verbose_name="Payment type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
