# Generated by Django 4.1.4 on 2023-03-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nova_poshta", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
        migrations.RemoveField(
            model_name="order",
            name="street",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Адреса"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Повідомлення"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="name", max_length=512, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="nova_poshta.settlement",
                verbose_name="Місто",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="surname",
            field=models.CharField(
                default="surname", max_length=512, verbose_name="Прізвище"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                max_length=512,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="nova_poshta.warehouse",
                verbose_name="Відділення",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(max_length=128, verbose_name="Спосіб оплати"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Телефон"
            ),
        ),
    ]
