# Generated by Django 4.1.4 on 2023-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_apartment_remove_order_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.CharField(default="f", max_length=512, verbose_name="Email"),
            preserve_default=False,
        ),
    ]
