# Generated by Django 3.2.13 on 2023-05-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
